export const SEARCH_REPO_REQUEST = "SEARCH_REPO_REQUEST";
export const SEARCH_REPO_SUCCESS = "SEARCH_REPO_SUCCESS";
export const SEARCH_REPO_FAILURE = "SEARCH_REPO_FAILURE";
export const SEARCH_CLEAR_REPO = "SEARCH_CLEAR_REPO";
export const SEARCH_REPO_HISTORY = "SEARCH_REPO_HISTORY";
export const SEARCH_REPO_HISTORY_CLEAR = "SEARCH_REPO_HISTORY_CLEAR";
export const SEARCH_VALUE = "SEARCH_VALUE";
export const SEARCH_SHWO_HISTORY = "SEARCH_SHWO_HISTORY";
